export const tiposDeArchivo: { nombre: string, icono: string }[] = [
    { nombre: 'PDF', icono: 'fas fa-file-pdf' },
    { nombre: 'Word', icono: 'fas fa-file-word' },
    { nombre: 'Excel', icono: 'fas fa-file-excel' },
    { nombre: 'PowerPoint', icono: 'fas fa-file-powerpoint' },
    { nombre: 'Imagen', icono: 'fas fa-file-image' },
    { nombre: 'Audio', icono: 'fas fa-file-audio' },
    { nombre: 'Video', icono: 'fas fa-file-video' },
    { nombre: 'Texto', icono: 'fas fa-file-alt' },
    { nombre: 'CSV', icono: 'fas fa-file-csv' },
    { nombre: 'ZIP', icono: 'fas fa-file-archive' },
    { nombre: 'RAR', icono: 'fas fa-file-archive' },
    { nombre: 'Presentación', icono: 'fas fa-file-powerpoint' },
    { nombre: 'HTML', icono: 'fas fa-file-code' },
    { nombre: 'XML', icono: 'fas fa-file-code' },
    { nombre: 'JSON', icono: 'fas fa-file-code' },
    { nombre: 'Archivo de Texto', icono: 'fas fa-file-alt' },
    { nombre: 'Archivo de Configuración', icono: 'fas fa-cogs' },
    { nombre: 'Base de Datos', icono: 'fas fa-database' },
    { nombre: 'Java', icono: 'fas fa-coffee' },
    { nombre: 'JavaScript', icono: 'fab fa-js' },
    { nombre: 'CSS', icono: 'fab fa-css3-alt' },
    { nombre: 'Markdown', icono: 'fab fa-markdown' },
    // Agrega más tipos de archivo según tus necesidades
  ];